// <auto-generated />
using System;
using ActionHistoryApp.API.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ActionHistoryApp.API.Persistence.Data.Migrations
{
    [DbContext(typeof(BlazingActionsContext))]
    [Migration("20260216112537_InitialEntities")]
    partial class InitialEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("ActionHistoryApp.API.Persistence.Entities.ActionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataBaseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatDid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WhenDid")
                        .HasColumnType("TEXT");

                    b.Property<string>("WhoDid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Actions");
                });
#pragma warning restore 612, 618
        }
    }
}
